name: Run test scripts on PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Verify forge install
        run: forge --version

      - name: Make test scripts executable
        run: |
          chmod +x ./test_patch.sh || true
          chmod +x ./test_original.sh || true

      - name: Run test_patch.sh (if present anywhere)
        continue-on-error: true
        run: |
            set -e
            patch_script=$(find . -type f -name test_patch.sh | head -n 1)
            if [ -n "$patch_script" ]; then
             echo "Found patch script at: $patch_script"
             chmod +x "$patch_script"
            "$patch_script"
            else
             echo "test_patch.sh not found."
             fi

      - name: Run test_original.sh (if present anywhere)
        run: |
            set -e
            original_script=$(find . -type f -name test_original.sh | head -n 1)
            if [ -n "$original_script" ]; then
             echo "Found original script at: $original_script"
             chmod +x "$original_script"
            "$original_script"
            else
             echo "test_original.sh not found."
             fi

